from dataModules.mnistSparseDataModule import *
from dataModules.mnist_OR_DataModule import *
from dataModules.mnist_OR_16_DataModule import *
from dataModules.mnist_RP_16_DataModule import *
from dataModules.mnist_OR_16_Block_DataModule import *
from dataModules.mnistBWDataModule import *
from dataModules.mnistGraphDataModule import *
from dataModules.mnistSuperpixelDataModule import *
from dataModules.mnist_CP_128_DataModule import *
from dataModules.mnist_SP_128_DataModule import *
from dataModules.mnist_CP_64_DataModule import *
from dataModules.mnist_SP_64_DataModule import *
from dataModules.mnist_CP_64_Pure_DataModule import *
from dataModules.mnist_CP_32_Pure_DataModule import *
from dataModules.mnist_CP_16_Pure_DataModule import *
from dataModules.mnist_CP_784_Pure_DataModule import *
from dataModules.mnist_CTP_64_Pure_DataModule import *